name: Test

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  bats:
    name: bats-core Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run tests
        run: make test
